### ISSUE TITLE
Repo URL

### ISSUE THREAD

**Issue by szepeviktor** [jmtd/debian-docker#19]
Please set repo URL here on GitHub

https://hub.docker.com/r/jmtd/debian/

**Comment by jmtd** [comment]
Hi, I don't quite understand what you are asking. Just to link to that from the README?

**Comment by szepeviktor** [comment]
Click on the <kbd> Edit </kbd> link on this page: https://github.com/jmtd/debian-docker

**Comment by szepeviktor** [comment]
At the top right. See this example: https://github.com/szepeviktor/debian-docker

**Comment by jmtd** [comment]
I see, thanks! Done.

**Comment by szepeviktor** [comment]
Thank you!

Could you add the GitHub URL to the description here https://hub.docker.com/r/jmtd/debian/ ?
