### ISSUE TITLE
Integrate option to ease rebuilding a base image

### ISSUE THREAD

**Issue by paulmenzel** [jmtd/debian-docker#5]
Currently running `sudo make` a second time, Docker uses the existing images from its cache.

I think that this is not desired, but I have not investigated the effects on for example the size of the image if updating the packages in the Dockerfile is enough.

Currently I am thinking about passing the switch `--no-cache=true` to `docker build`.

Another workaround is to do `sudo git clean -dfx` to remove all files, including the roots, not in the repository.

**Comment by jmtd** [comment]
This is by design, really: it follows the docker default of using its cache. I'd consider adding support for passing `--no-cache=true` to the docker invocation as an option.
